"""
post_hoc_analysis.py  (7-way, vectorised)
===========================================
Standalone analysis script that loads a previously trained 7-WAY Random
Forest model (L2 core0/1, L3, BTB core0/1, Prefetcher core0/1) and runs the
following analyses on the full dataset:

  1. PPW % LOSS ANALYSIS          — how much PPW do we lose vs optimal?
  2. STATIC BASELINE COMPARISON   — vs best-static, worst-static, optimal
  3. BEST vs 2ND-BEST GAP         — how much headroom is there to be wrong?
  4. NO-CHANGE BASELINE           — if prev config kept, is it still top-3?
  5. INFERENCE & RECONFIG COST    — McPAT/GAINESTOWN energy overhead

For rows where the model's prediction doesn't match the oracle's top-3
(1st/2nd/3rd) config for that period, the ACTUAL achieved PPW of the
predicted config is looked up from merged_full_<bench>.csv -- the full
per-(period, every-candidate-config) sweep -- rather than assumed to equal
ppw_3rd. Analysis 2's static baselines are likewise computed from that same
full sweep (average PPW per candidate config across every period, take the
max), not from the top-3-only file, since the top-3 file cannot correctly
answer "what would config X average across the whole benchmark" -- it only
records periods where X happened to BE in the top 3.

Usage:
    python post_hoc_analysis.py --merged-full-dir /path/to/merged_full/
    python post_hoc_analysis.py --model-dir saved_models/ --merged-full-dir /path/to/merged_full/
    python post_hoc_analysis.py --model-dir saved_models/ --model-timestamp 20240101_120000 \\
        --merged-full-dir /path/to/merged_full/
"""

import os
import sys
import glob
import argparse
import warnings
from datetime import datetime

import numpy as np
import pandas as pd
import joblib
import matplotlib
matplotlib.use('Agg')  # headless -- this script runs without a display
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer

warnings.filterwarnings('ignore')

# ══════════════════════════════════════════════════════════════════════════════
# COLUMN NAME RESOLUTION HELPERS  (must match rf_7way_config_predictor.py)
# ══════════════════════════════════════════════════════════════════════════════

def _normalize_name(s):
    return s.lower().replace('_', '').replace(' ', '').replace('.', '')


def find_col(df, expected_name):
    """Find a column matching expected_name, ignoring case/separators."""
    norm = _normalize_name
    for col in df.columns:
        if norm(col) == norm(expected_name):
            return col
    for col in df.columns:
        if norm(expected_name) in norm(col):
            return col
    return None


CONFIG_DIMENSIONS = {
    'l2_core0':        'L2core0',
    'l2_core1':        'L2core1',
    'l3':              'L3',
    'btb_core0':       'BTBcore0',
    'btb_core1':       'BTBcore1',
    'prefetch_core0':  'Prefetchcore0',
    'prefetch_core1':  'Prefetchcore1',
}
RANKS = ['best', '2nd', '3rd']

TARGET_KEYS = ['l2_core0', 'l2_core1', 'l3', 'btb_core0', 'btb_core1',
               'prefetch_core0', 'prefetch_core1']

NUMERIC_TARGET_KEYS = ['l2_core0', 'l2_core1', 'l3', 'btb_core0', 'btb_core1']
PREFETCH_KEYS = ['prefetch_core0', 'prefetch_core1']


def canonical_name(key, rank):
    return f"{key}__{rank}"


def resolve_config_columns(df):
    resolved = {}
    missing = []
    for key, template in CONFIG_DIMENSIONS.items():
        for rank in RANKS:
            expected = f"{template}_{rank}"
            actual = find_col(df, expected)
            if actual is None:
                missing.append(expected)
            else:
                resolved[(key, rank)] = actual
    if missing:
        raise ValueError(
            f"Could not resolve the following expected config columns "
            f"(tried case/separator-insensitive matching): {missing}\n"
            f"Available columns: {list(df.columns)}\n"
            f"Was this file generated by the updated find_top3_configs_by_ppw / "
            f"merge_train_with_top3 scripts?"
        )
    ppw_cols = {}
    for rank in RANKS:
        actual = find_col(df, f"PPW_{rank}")
        if actual is None:
            raise ValueError(f"Could not resolve PPW_{rank} column. Available: {list(df.columns)}")
        ppw_cols[rank] = actual
    return resolved, ppw_cols


def normalize_config(vals):
    try:
        l2_0, l2_1, l3, btb0, btb1, pf0, pf1 = vals
        return (float(l2_0), float(l2_1), float(l3), float(btb0), float(btb1),
                int(pf0), int(pf1))
    except (ValueError, TypeError):
        return None


PREV_DIMENSIONS = {
    'l2_core0':       ['L2 core 0_prev', 'L2core0_prev', 'l2Core0_prev'],
    'l2_core1':       ['L2 core 1_prev', 'L2core1_prev', 'l2Core1_prev'],
    'l3':             ['L3_prev', 'l3Size_prev'],
    'btb_core0':      ['BTB core 0_prev', 'BTBcore0_prev', 'btbCore0_prev'],
    'btb_core1':      ['BTB core 1_prev', 'BTBcore1_prev', 'btbCore1_prev'],
    'prefetch_core0': ['Prefetch core 0_prev', 'prefetcher_core0_prev', 'Prefetch_core0_prev', 'Prefetch_prev'],
    'prefetch_core1': ['Prefetch core 1_prev', 'prefetcher_core1_prev', 'Prefetch_core1_prev'],
}


def resolve_first_present(df, candidates):
    for c in candidates:
        found = find_col(df, c)
        if found:
            return found
    return None


# ══════════════════════════════════════════════════════════════════════════════
# CLI
# ══════════════════════════════════════════════════════════════════════════════
parser = argparse.ArgumentParser(description='Post-hoc 7-way RF model analysis')
parser.add_argument('--model-dir', type=str, default='saved_models/')
parser.add_argument('--model-timestamp', type=str, default=None,
                    help='Specific timestamp to load (e.g. 20240101_120000). '
                         'If omitted, loads the most recent model.')
parser.add_argument('--output-dir', type=str, default='analysis_reports/',
                    help='Directory to save the text report')
parser.add_argument('--cost-csv', type=str, default=None,
                    help='Optional CSV from costAnalysis.py with inference/reconfig costs')
parser.add_argument('--merged-full-dir', type=str, default=None, required=True,
                    help="Directory containing merged_full_<bench>.csv (the full per-period, "
                         "every-candidate-config sweep -- NOT the top-3-only file). Used to get the "
                         "REAL achieved PPW when the model's prediction misses the top-3 (instead of "
                         "assuming it equals ppw_3rd), and to compute Analysis 2's static baselines "
                         "correctly (avg PPW per config across the whole benchmark, not just periods "
                         "where that config happened to rank in the top 3).")
parser.add_argument('--merged-full-chunksize', type=int, default=200_000)

args = parser.parse_args()

os.makedirs(args.output_dir, exist_ok=True)

MERGED_FULL_FILES = {
    bench: os.path.join(args.merged_full_dir, f'merged_full_{bench}.csv')
    for bench in ['barnes', 'cholesky', 'radiosity', 'fft']
}

# merged_full_<bench>.csv column candidates -- this file has NO "_prev"
# suffix ambiguity: period_start/period_end are this row's own current
# interval, the config columns identify this row's own config, and 'ppw'
# is that exact config's real achieved PPW for that exact interval.
MERGED_FULL_PERIOD_CANDIDATES = ['period_start']
MERGED_FULL_PPW_CANDIDATES = ['ppw']
MERGED_FULL_CONFIG_DIMS = {
    'l2_core0':       ['l2Core0', 'L2core0', 'L2 core 0'],
    'l2_core1':       ['l2Core1', 'L2core1', 'L2 core 1'],
    'l3':             ['l3Size', 'L3'],
    'btb_core0':      ['btbCore0', 'BTBcore0', 'BTB core 0'],
    'btb_core1':      ['btbCore1', 'BTBcore1', 'BTB core 1'],
    'prefetch_core0': ['prefetchCore0', 'Prefetchcore0', 'Prefetch core 0'],
    'prefetch_core1': ['prefetchCore1', 'Prefetchcore1', 'Prefetch core 1'],
}


def resolve_col(columns, candidates):
    """Like resolve_first_present, but takes a bare list of column names
    instead of a DataFrame (for reading just a CSV header)."""
    dummy = pd.DataFrame(columns=columns)
    return resolve_first_present(dummy, candidates)


def parse_period_numeric(period_val):
    """Extract the numeric instruction-count id from a period label.
    Handles 'periodicins-100000002' -> 100000002, bare numbers -> as-is,
    and non-numeric sentinels ('roi-begin', 'roi-end', etc.) -> None."""
    if period_val is None:
        return None
    if isinstance(period_val, (int, float)) and not isinstance(period_val, bool):
        return None if (isinstance(period_val, float) and np.isnan(period_val)) else float(period_val)
    s = str(period_val).strip()
    if s.lower() in ('nan', ''):
        return None
    if '-' in s:
        tail = s.rsplit('-', 1)[-1]
        if tail.replace('.', '', 1).isdigit():
            return float(tail)
        return None
    if s.replace('.', '', 1).isdigit():
        return float(s)
    return None


def normalize_component(val):
    """Normalize one config-dimension value for equality comparison across
    files that may format the same value as '512', '512.0', 512.0, 'none', etc."""
    try:
        f = float(val)
        if np.isnan(f):
            return None
        return round(f, 6)
    except (TypeError, ValueError):
        s = str(val).strip().lower()
        return None if s in ('nan', '') else s


def process_merged_full(bench, path, needed_pairs, chunksize=200_000):
    """
    Single streaming pass over merged_full_<bench>.csv, serving both fixes
    at once:
      - pair_lookup: {(period_num, cfg_tuple): ppw} for exactly the
        (period, predicted-config) pairs in needed_pairs -- used to get the
        REAL achieved PPW for rows where the model's prediction missed the
        top-3 (instead of assuming ppw_3rd).
      - static_sum / static_count: per-config running totals across EVERY
        row (every period, every candidate config) in the file -- the
        correct data for "what would config X average across the whole
        benchmark", which the top-3-only file cannot answer.
    """
    if not os.path.exists(path):
        raise FileNotFoundError(f"merged_full file not found for benchmark '{bench}': {path}")

    header_cols = list(pd.read_csv(path, nrows=0).columns)
    period_col = resolve_col(header_cols, MERGED_FULL_PERIOD_CANDIDATES)
    ppw_col = resolve_col(header_cols, MERGED_FULL_PPW_CANDIDATES)
    dim_cols = {k: resolve_col(header_cols, cands) for k, cands in MERGED_FULL_CONFIG_DIMS.items()}
    bench_col = resolve_col(header_cols, ['benchmark'])
    missing = [k for k, v in dim_cols.items() if v is None]
    if period_col is None or ppw_col is None or missing:
        raise ValueError(f"Could not resolve required column(s) in {path}: "
                          f"period_start={period_col}, ppw={ppw_col}, missing config dims={missing}")

    usecols = [period_col, ppw_col] + list(dim_cols.values())
    if bench_col:
        usecols.append(bench_col)
    usecols = list(dict.fromkeys(usecols))

    pair_lookup = {}
    static_sum = {}
    static_count = {}
    n_rows = 0
    periods_needed = {p for p, _ in needed_pairs}

    for chunk in pd.read_csv(path, usecols=usecols, chunksize=chunksize, low_memory=False):
        n_rows += len(chunk)
        if bench_col and bench_col in chunk.columns:
            chunk = chunk[chunk[bench_col].astype(str).str.lower() == bench.lower()]
            if chunk.empty:
                continue

        period_nums = chunk[period_col].map(parse_period_numeric)
        ppw_vals = pd.to_numeric(chunk[ppw_col], errors='coerce')
        finite = np.isfinite(ppw_vals) & period_nums.notna()
        if not finite.any():
            continue
        sub = chunk.loc[finite]
        sub_periods = period_nums.loc[finite]
        sub_ppw = ppw_vals.loc[finite]

        config_key = pd.Series(
            list(zip(*[sub[dim_cols[k]].map(normalize_component) for k in TARGET_KEYS])),
            index=sub.index,
        )

        # static accumulation -- every row, every config
        for key, val in zip(config_key, sub_ppw):
            static_sum[key] = static_sum.get(key, 0.0) + val
            static_count[key] = static_count.get(key, 0) + 1

        # targeted lookup -- only the (period, config) pairs we actually need
        if periods_needed:
            in_needed_period = sub_periods.isin(periods_needed)
            if in_needed_period.any():
                for period, cfg, val in zip(sub_periods[in_needed_period],
                                             config_key[in_needed_period],
                                             sub_ppw[in_needed_period]):
                    pair = (period, cfg)
                    if pair in needed_pairs and pair not in pair_lookup:
                        pair_lookup[pair] = val

    return pair_lookup, static_sum, static_count, n_rows

# ══════════════════════════════════════════════════════════════════════════════
# DATA FILES
# ══════════════════════════════════════════════════════════════════════════════
DATA_FILES = {
    'barnes':    '/home/gina/Desktop/snipersim_framework/pythonScripts/barnes/train_with_top3_barnes.csv',
    'cholesky':  '/home/gina/Desktop/snipersim_framework/pythonScripts/cholesky/train_with_top3_cholesky.csv',
    'fft': '/home/gina/Desktop/snipersim_framework/pythonScripts/fft/train_with_top3_fft.csv',
  'radiosity': '/home/gina/Desktop/snipersim_framework/pythonScripts/radiosity/train_with_top3_radiosity.csv',
}

METADATA_COLUMNS_TO_DROP = [
    'best-config', 'file', 'file_prev', 'period_start',
    'period_end', 'period_start_prev', 'period_end_prev',
    'directory_perf_prev', 'leaf_dir_prev', 'directory_power_prev',
    'leaf_dir_perf_prev', 'leaf_dir_power_prev', 'period_start_val_prev',
    'period_end_val_perf_prev', 'period_start_val_perf_prev',
    'period_start_val_power_prev', 'period_end_val_power_prev',
    'Diff_best_2nd', 'Diff_best_3rd',
]

RANDOM_STATE = 42

# ══════════════════════════════════════════════════════════════════════════════
# OUTPUT HELPERS
# ══════════════════════════════════════════════════════════════════════════════
report_lines = []

def out(line=''):
    print(line)
    report_lines.append(str(line))

def section(title):
    out(); out('═' * 65); out(f'  {title}'); out('═' * 65)

def subsection(title):
    out(); out(f'  ── {title}'); out('  ' + '─' * 55)

def pct_str(n, total):
    return f'{int(n):>6,}  ({n/total*100:5.1f}%)'

def stats_str(series, unit='%'):
    s = series.dropna()
    if len(s) == 0:
        return '  no data'
    return (f'  mean={s.mean():.2f}{unit}  median={s.median():.2f}{unit}'
            f'  p90={np.percentile(s, 90):.2f}{unit}  max={s.max():.2f}{unit}')

def loss_buckets(series, n_total, label=''):
    s = series.dropna()
    out(f'    {label}Loss distribution (% of {n_total:,} total samples):')
    boundaries = [
        (None, 0,   '0%  (exact match)     '),
        (0,    1,   '0-1%                  '),
        (1,    5,   '1-5%                  '),
        (5,    10,  '5-10%                 '),
        (10,   20,  '10-20%                '),
        (20,   None,'>20%                  '),
    ]
    for lo, hi, lbl in boundaries:
        if lo is None:
            cnt = (s == 0.0).sum()
        elif hi is None:
            cnt = (s > lo).sum()
        else:
            cnt = ((s > lo) & (s <= hi)).sum()
        out(f'      {lbl}  {cnt:>6,}  ({cnt/n_total*100:5.1f}%)')


# ══════════════════════════════════════════════════════════════════════════════
# 1.  LOAD MODEL  (rf_7way_config_predictor_*.pkl)
# ══════════════════════════════════════════════════════════════════════════════
section('LOADING SAVED MODEL')

model_dir = args.model_dir
if args.model_timestamp:
    ts = args.model_timestamp
else:
    pkls = glob.glob(os.path.join(model_dir, 'rf_7way_config_predictor_*.pkl'))
    pkls = [p for p in pkls if not any(x in p for x in
                                        ['_scaler', '_encoder', '_prefetcher'])]
    if not pkls:
        out(f'ERROR: No 7-way model files found in {model_dir}'); sys.exit(1)
    ts = os.path.basename(sorted(pkls)[-1]) \
           .replace('rf_7way_config_predictor_', '').replace('.pkl', '')

def mpath(suffix=''):
    return os.path.join(model_dir, f'rf_7way_config_predictor_{ts}{suffix}.pkl')

for p in [mpath(), mpath('_scaler'),
          mpath('_prefetcher_core0_encoder'),
          mpath('_prefetcher_core1_encoder')]:
    if not os.path.exists(p):
        out(f'ERROR: File not found: {p}'); sys.exit(1)

model   = joblib.load(mpath())
scaler  = joblib.load(mpath('_scaler'))
enc_pf0 = joblib.load(mpath('_prefetcher_core0_encoder'))
enc_pf1 = joblib.load(mpath('_prefetcher_core1_encoder'))
PF_ENCODERS = {'prefetch_core0': enc_pf0, 'prefetch_core1': enc_pf1}

out(f'  Timestamp:    {ts}')
out(f'  n_estimators: {model.n_estimators}  '
    f'max_depth: {model.max_depth}  '
    f'max_features: {model.max_features}')
out(f'  Targets ({len(TARGET_KEYS)}): {TARGET_KEYS}')


# ══════════════════════════════════════════════════════════════════════════════
# 2.  LOAD DATA
# ══════════════════════════════════════════════════════════════════════════════
section('LOADING & PREPROCESSING DATA')

frames = []
for bench, path in DATA_FILES.items():
    if not os.path.exists(path):
        out(f'  [WARN] File not found, skipping: {path}'); continue
    df_b = pd.read_csv(path, low_memory=False)
    df_b['benchmark'] = bench
    frames.append(df_b)
    out(f'  Loaded {bench}: {df_b.shape[0]:,} rows')

df_full = pd.concat(frames, ignore_index=True)
out(f'  Combined: {df_full.shape[0]:,} rows')

resolved_cols, ppw_cols = resolve_config_columns(df_full)

out('  Resolved config columns:')
for (key, rank), actual in sorted(resolved_cols.items()):
    out(f'    {key} ({rank}) -> {actual}')
for rank, actual in ppw_cols.items():
    out(f'    PPW ({rank}) -> {actual}')

rename_map = {}
for (key, rank), actual in resolved_cols.items():
    rename_map[actual] = canonical_name(key, rank)
for rank, actual in ppw_cols.items():
    rename_map[actual] = f'PPW__{rank}'
df_full = df_full.rename(columns=rename_map)

TARGET_COLUMNS = [canonical_name(k, 'best') for k in TARGET_KEYS]
ALL_CONFIG_COLUMNS = []
for rank in RANKS:
    for k in TARGET_KEYS:
        ALL_CONFIG_COLUMNS.append(canonical_name(k, rank))
    ALL_CONFIG_COLUMNS.append(f'PPW__{rank}')

prev_col_map = {}
for key, candidates in PREV_DIMENSIONS.items():
    prev_col_map[key] = resolve_first_present(df_full, candidates)
prev_config_available = all(v is not None for v in prev_col_map.values())
if not prev_config_available:
    out('  [WARN] Previous-config columns not all found — Analysis 4 will be skipped.')
    out(f'    Resolved prev columns: {prev_col_map}')

top3_raw = df_full[ALL_CONFIG_COLUMNS + ['benchmark']].copy()

period_start_col = find_col(df_full, 'period_start')
if period_start_col is None:
    out('  [WARN] No period_start column found -- cannot join against merged_full for miss rows.')
    period_raw = None
else:
    period_raw = df_full[[period_start_col]].copy()
    period_raw.columns = ['period_start']

if prev_config_available:
    prev_raw = df_full[list(prev_col_map.values())].copy()
    prev_raw.columns = [f'{key}__prev' for key in prev_col_map.keys()]

df    = df_full.drop(columns=METADATA_COLUMNS_TO_DROP, errors='ignore')
X_raw = df.drop(columns=ALL_CONFIG_COLUMNS, errors='ignore')
y_raw = df[TARGET_COLUMNS].copy()

benchmark_col = X_raw['benchmark'].copy() if 'benchmark' in X_raw.columns else None

for col in X_raw.select_dtypes(include=['object']).columns:
    le = LabelEncoder()
    X_raw[col] = le.fit_transform(X_raw[col].astype(str))

def safe_encode_series(encoder, series):
    valid = set(encoder.classes_)
    s = series.fillna('none').astype(str).str.strip().str.lower()
    s = s.apply(lambda x: x if x in valid else 'none')
    return encoder.transform(s).astype(int)

for key in NUMERIC_TARGET_KEYS:
    col = canonical_name(key, 'best')
    y_raw[col] = pd.to_numeric(y_raw[col], errors='coerce')
for key in PREFETCH_KEYS:
    col = canonical_name(key, 'best')
    y_raw[col] = safe_encode_series(PF_ENCODERS[key], y_raw[col])

X_num = X_raw.select_dtypes(include=[np.number])

mask_valid  = y_raw.notna().all(axis=1).values
imputer     = SimpleImputer(strategy='mean')
X_scaled    = imputer.fit_transform(X_num)
X_scaled    = scaler.transform(X_scaled)
X_scaled    = X_scaled[mask_valid]

y_valid     = y_raw[mask_valid].reset_index(drop=True)
top3_valid  = top3_raw[mask_valid].reset_index(drop=True)
period_valid = period_raw[mask_valid].reset_index(drop=True) if period_raw is not None else None
bench_valid = benchmark_col[mask_valid].reset_index(drop=True) \
              if benchmark_col is not None else None
if prev_config_available:
    prev_valid = prev_raw[mask_valid].reset_index(drop=True)

out(f'  Valid samples after NaN drop: {len(y_valid):,}')


# ══════════════════════════════════════════════════════════════════════════════
# 3.  PREDICT
# ══════════════════════════════════════════════════════════════════════════════
section('RUNNING PREDICTIONS')
t0     = datetime.now()
y_pred = model.predict(X_scaled)
out(f'  Predicted {len(y_pred):,} samples in '
    f'{(datetime.now()-t0).total_seconds():.1f}s')

if y_pred.shape[1] != len(TARGET_KEYS):
    out(f'  ERROR: model outputs {y_pred.shape[1]} targets but expected '
        f'{len(TARGET_KEYS)} ({TARGET_KEYS}). Is this really a 7-way model?')
    sys.exit(1)


# ══════════════════════════════════════════════════════════════════════════════
# 4.  VECTORISED RESULTS TABLE  (no per-row Python loops)
# ══════════════════════════════════════════════════════════════════════════════
section('BUILDING RESULTS TABLE  (vectorised)')

def encode_pf_col(key, series):
    encoder = PF_ENCODERS[key]
    valid = set(encoder.classes_)
    s = series.fillna('none').astype(str).str.strip().str.lower()
    s = s.apply(lambda x: x if x in valid else 'none')
    return encoder.transform(s).astype(int)

def numeric_col(series):
    return pd.to_numeric(series, errors='coerce').values.astype(float)

pred_vals = {}
for idx, key in enumerate(TARGET_KEYS):
    if key in PREFETCH_KEYS:
        pred_vals[key] = y_pred[:, idx].astype(int)
    else:
        pred_vals[key] = y_pred[:, idx].astype(float)

true_vals = {}
for key in TARGET_KEYS:
    col = canonical_name(key, 'best')
    true_vals[key] = y_valid[col].values.astype(int if key in PREFETCH_KEYS else float)

rank_vals = {'2nd': {}, '3rd': {}}
for rank in ['2nd', '3rd']:
    for key in TARGET_KEYS:
        col = canonical_name(key, rank)
        if key in PREFETCH_KEYS:
            rank_vals[rank][key] = encode_pf_col(key, top3_valid[col])
        else:
            rank_vals[rank][key] = numeric_col(top3_valid[col])

ppw_best = numeric_col(top3_valid['PPW__best'])
ppw_2nd  = numeric_col(top3_valid['PPW__2nd'])
ppw_3rd  = numeric_col(top3_valid['PPW__3rd'])

def all_match(vals_a, vals_b):
    m = np.ones(len(ppw_best), dtype=bool)
    for key in TARGET_KEYS:
        m &= (vals_a[key] == vals_b[key])
    return m

match_best = all_match(pred_vals, true_vals)
match_2nd  = all_match(pred_vals, rank_vals['2nd'])
match_3rd  = all_match(pred_vals, rank_vals['3rd'])
match_top3 = match_best | match_2nd | match_3rd

out(f'  Exact match:  {match_best.sum():,}  ({match_best.mean()*100:.2f}%)')
out(f'  Top-3 match:  {match_top3.sum():,}  ({match_top3.mean()*100:.2f}%)')
assert match_top3.sum() >= match_best.sum(), 'BUG: top3 < exact'

numpy_exact = (y_valid.values == y_pred).all(axis=1).sum()
out(f'  Numpy exact check: {numpy_exact:,}  '
    f'{"[OK]" if numpy_exact == match_best.sum() else "[WARN mismatch]"}')

out('  Per-dimension accuracy:')
for key in TARGET_KEYS:
    acc = (pred_vals[key] == true_vals[key]).mean()
    out(f'    {key:<16} {acc:.4f}')

has_ppw = ~np.isnan(ppw_best) & (ppw_best != 0)

miss_pred_mask = ~match_top3

if prev_config_available:
    prev_vals = {}
    for key in TARGET_KEYS:
        col = f'{key}__prev'
        if key in PREFETCH_KEYS:
            prev_vals[key] = encode_pf_col(key, prev_valid[col])
        else:
            prev_vals[key] = numeric_col(prev_valid[col])

    prev_match_best = all_match(prev_vals, true_vals)
    prev_match_2nd  = all_match(prev_vals, rank_vals['2nd'])
    prev_match_3rd  = all_match(prev_vals, rank_vals['3rd'])
    prev_match_top3 = prev_match_best | prev_match_2nd | prev_match_3rd
    miss_prev_mask = ~prev_match_top3
else:
    miss_prev_mask = np.zeros(len(ppw_best), dtype=bool)

# ─────────────────────────────────────────────────────────────────────────
# Resolve REAL achieved PPW for miss rows (both the model's prediction and,
# if available, the no-change/previous-config baseline) from
# merged_full_<bench>.csv, instead of assuming a miss performs like
# ppw_3rd. Also gather the full per-config PPW aggregation needed to fix
# Analysis 2's static baselines in the same pass.
# ─────────────────────────────────────────────────────────────────────────
section('RESOLVING MISS-ROW PPW FROM merged_full (per benchmark)')

def decode_tuples_for_mask(vals_dict, mask):
    """Build {row_index: normalized_cfg_tuple} for rows where mask is True,
    decoding label-encoded prefetch values back to their string labels."""
    idxs = np.where(mask)[0]
    if len(idxs) == 0:
        return {}
    decoded = {}
    for key in TARGET_KEYS:
        arr = vals_dict[key][idxs]
        if key in PREFETCH_KEYS:
            decoded[key] = PF_ENCODERS[key].inverse_transform(arr.astype(int))
        else:
            decoded[key] = arr.astype(float)
    out_map = {}
    for i, row_idx in enumerate(idxs):
        out_map[int(row_idx)] = tuple(normalize_component(decoded[key][i]) for key in TARGET_KEYS)
    return out_map

period_nums_all = (period_valid['period_start'].map(parse_period_numeric).values
                    if period_valid is not None else np.full(len(ppw_best), None))

pred_cfg_by_row = decode_tuples_for_mask(pred_vals, miss_pred_mask)
prev_cfg_by_row = decode_tuples_for_mask(prev_vals, miss_prev_mask) if prev_config_available else {}

pred_achieved_ppw = np.full(len(ppw_best), np.nan)
prev_achieved_ppw = np.full(len(ppw_best), np.nan)
static_configs = {}
n_pred_miss_resolved = {}
n_pred_miss_total = {}
n_prev_miss_resolved = {}
n_prev_miss_total = {}

bench_array = bench_valid.values if bench_valid is not None else np.array(['unknown'] * len(ppw_best))

for bench in DATA_FILES.keys():
    bench_row_idx = np.where(bench_array == bench)[0]
    bench_row_set = set(bench_row_idx.tolist())

    needed_pairs = set()
    for row_idx, cfg in pred_cfg_by_row.items():
        if row_idx in bench_row_set and period_nums_all[row_idx] is not None and all(c is not None for c in cfg):
            needed_pairs.add((period_nums_all[row_idx], cfg))
    for row_idx, cfg in prev_cfg_by_row.items():
        if row_idx in bench_row_set and period_nums_all[row_idx] is not None and all(c is not None for c in cfg):
            needed_pairs.add((period_nums_all[row_idx], cfg))

    path = MERGED_FULL_FILES.get(bench)
    if path is None or not os.path.exists(path):
        out(f'  [WARN] {bench}: merged_full file not found at {path} -- miss rows will fall back to '
            f'ppw_3rd for this benchmark, and Analysis 2 static baselines will be skipped.')
        continue

    pair_lookup, static_sum, static_count, n_rows_read = process_merged_full(
        bench, path, needed_pairs, chunksize=args.merged_full_chunksize
    )
    out(f'  {bench}: read {n_rows_read:,} rows from {path}, '
        f'resolved {len(pair_lookup):,}/{len(needed_pairs):,} needed (period, config) pairs, '
        f'{len(static_count):,} distinct candidate configs seen.')

    n_pred_resolved = n_pred_total = 0
    for row_idx, cfg in pred_cfg_by_row.items():
        if row_idx not in bench_row_set:
            continue
        n_pred_total += 1
        val = pair_lookup.get((period_nums_all[row_idx], cfg))
        if val is not None:
            pred_achieved_ppw[row_idx] = val
            n_pred_resolved += 1
    n_pred_miss_resolved[bench] = n_pred_resolved
    n_pred_miss_total[bench] = n_pred_total

    n_prev_resolved = n_prev_total = 0
    for row_idx, cfg in prev_cfg_by_row.items():
        if row_idx not in bench_row_set:
            continue
        n_prev_total += 1
        val = pair_lookup.get((period_nums_all[row_idx], cfg))
        if val is not None:
            prev_achieved_ppw[row_idx] = val
            n_prev_resolved += 1
    n_prev_miss_resolved[bench] = n_prev_resolved
    n_prev_miss_total[bench] = n_prev_total

    if n_pred_total:
        out(f'  {bench}: {n_pred_resolved}/{n_pred_total} model-miss rows resolved to their real '
            f'achieved PPW ({n_pred_total - n_pred_resolved} still fall back to ppw_3rd -- their '
            f'predicted config/period combo was not found in merged_full).')
    if n_prev_total:
        out(f'  {bench}: {n_prev_resolved}/{n_prev_total} no-change-baseline-miss rows resolved to their '
            f'real achieved PPW ({n_prev_total - n_prev_resolved} fall back to ppw_3rd).')

    # Analysis 2 fix: true per-config average PPW across the WHOLE benchmark
    # (every period, this exact config), not just periods where the config
    # happened to be in the top-3.
    if static_count:
        means = {k: static_sum[k] / static_count[k] for k in static_count}
        best_key = max(means, key=means.get)
        worst_key = min(means, key=means.get)
        static_configs[bench] = {
            'best_static':          best_key,
            'worst_static':         worst_key,
            'best_static_avg_ppw':  means[best_key],
            'worst_static_avg_ppw': means[worst_key],
            'best_static_n_samples': static_count[best_key],
            'worst_static_n_samples': static_count[worst_key],
            'max_n_samples':        max(static_count.values()),
            'optimal_avg_ppw':      np.nanmean(ppw_best[bench_row_idx]) if len(bench_row_idx) else np.nan,
        }
        out(f'  {bench}: best_static  = {best_key}  (avg PPW={means[best_key]:.4e}, '
            f'n={static_count[best_key]:,}/{static_configs[bench]["max_n_samples"]:,} periods)')
        out(f'  {"":10}  worst_static = {worst_key}  (avg PPW={means[worst_key]:.4e}, '
            f'n={static_count[worst_key]:,})')
        out(f'  {"":10}  (order: {TARGET_KEYS})')

# fill in pred_ppw / prev_ppw: real achieved value where resolved, else the
# original top-3-based logic (exact/2nd/3rd match, or ppw_3rd as last-resort
# fallback only when a genuine miss couldn't be resolved via merged_full)
pred_ppw = np.where(match_best, ppw_best,
           np.where(match_2nd,  ppw_2nd,
           np.where(match_3rd,  ppw_3rd,
           np.where(~np.isnan(pred_achieved_ppw), pred_achieved_ppw, ppw_3rd))))

pred_ppw_loss_pct = np.where(has_ppw,
                              (ppw_best - pred_ppw) / ppw_best * 100,
                              np.nan)
pred_ppw_loss_pct = np.where(match_best, 0.0, pred_ppw_loss_pct)

has_ppw_2nd      = ~np.isnan(ppw_2nd) & has_ppw
gap_best_2nd_pct = np.where(has_ppw_2nd,
                              (ppw_best - ppw_2nd) / ppw_best * 100,
                              np.nan)

if prev_config_available:
    prev_ppw = np.where(prev_match_best, ppw_best,
               np.where(prev_match_2nd,  ppw_2nd,
               np.where(prev_match_3rd,  ppw_3rd,
               np.where(~np.isnan(prev_achieved_ppw), prev_achieved_ppw, ppw_3rd))))
    prev_ppw_loss_pct = np.where(has_ppw,
                                  (ppw_best - prev_ppw) / ppw_best * 100,
                                  np.nan)
    prev_ppw_loss_pct = np.where(prev_match_best, 0.0, prev_ppw_loss_pct)

results_df = pd.DataFrame({
    'benchmark':         bench_valid.values if bench_valid is not None else 'unknown',
    'best_ppw':          ppw_best,
    'ppw_2nd':           ppw_2nd,
    'ppw_3rd':           ppw_3rd,
    'exact_match':       match_best,
    'top3_match':        match_top3,
    'match_2nd':         match_2nd,
    'match_3rd':         match_3rd,
    'pred_ppw_loss_pct': pred_ppw_loss_pct,
    'gap_best_2nd_pct':  gap_best_2nd_pct,
})
if prev_config_available:
    results_df['prev_is_best']      = prev_match_best
    results_df['prev_in_top3']      = prev_match_top3
    results_df['prev_ppw_loss_pct'] = prev_ppw_loss_pct

out(f'  Results table: {len(results_df):,} rows x {len(results_df.columns)} columns')

benchmarks = ['overall'] + sorted(results_df['benchmark'].unique().tolist())

def subset(bench):
    return results_df if bench == 'overall' \
           else results_df[results_df['benchmark'] == bench]


# ══════════════════════════════════════════════════════════════════════════════
# 5.  STATIC CONFIGS  -- already computed above (from merged_full, in the same
# pass as the miss-row PPW resolution). static_configs is populated there.
# ══════════════════════════════════════════════════════════════════════════════


# ══════════════════════════════════════════════════════════════════════════════
# 6.  PRINT ANALYSES
# ══════════════════════════════════════════════════════════════════════════════
out(f'\n  Analysis run: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}   |   Model: {ts}')

section('ANALYSIS 1 — PPW % LOSS  (Model Prediction vs Optimal)')

for bench in benchmarks:
    df_b = subset(bench)
    n    = len(df_b)
    subsection(bench.upper())
    out(f'    Samples: {n:,}')

    exact = df_b['exact_match'].sum()
    top3  = df_b['top3_match'].sum()
    m2    = df_b['match_2nd'].sum()
    m3    = df_b['match_3rd'].sum()

    out(f'    Exact match (1st):  {pct_str(exact, n)}')
    out(f'    Match 2nd best:     {pct_str(m2, n)}')
    out(f'    Match 3rd best:     {pct_str(m3, n)}')
    out(f'    Top-3 total:        {pct_str(top3, n)}')
    out(f'    Miss:               {pct_str(n - top3, n)}')

    loss = df_b['pred_ppw_loss_pct'].dropna()
    out(f'    PPW % loss stats:   {stats_str(loss)}')
    loss_buckets(df_b['pred_ppw_loss_pct'], n, label='Model prediction ')


# ─────────────────────────────────────────────────────────────────────────────
# PPW LOSS DISTRIBUTION PLOTS  (CDF, histogram, box plot)
# ─────────────────────────────────────────────────────────────────────────────
section('PPW LOSS DISTRIBUTION PLOTS')
plot_dir = os.path.join(args.output_dir, 'plots')
os.makedirs(plot_dir, exist_ok=True)
for bench in benchmarks:
    loss = subset(bench)['pred_ppw_loss_pct'].dropna()
    if loss.empty:
        out(f'  [SKIP] {bench}: no PPW loss data to plot')
        continue
    # Histogram
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.hist(loss, bins=50, color='steelblue', edgecolor='black')
    ax.set_xlabel('PPW % loss vs optimal'); ax.set_ylabel('Sample count')
    ax.set_title(f'PPW Loss Histogram — {bench}')
    fig.tight_layout()
    fig.savefig(os.path.join(plot_dir, f'ppw_loss_hist_{bench}.png'), dpi=150)
    plt.close(fig)
    # CDF
    fig, ax = plt.subplots(figsize=(8, 5))
    sorted_loss = np.sort(loss.values)
    cdf = np.arange(1, len(sorted_loss) + 1) / len(sorted_loss)
    ax.plot(sorted_loss, cdf, color='darkorange')
    ax.set_xlabel('PPW % loss vs optimal'); ax.set_ylabel('Cumulative fraction')
    ax.set_title(f'PPW Loss CDF — {bench}')
    ax.grid(True, alpha=0.3)
    fig.tight_layout()
    fig.savefig(os.path.join(plot_dir, f'ppw_loss_cdf_{bench}.png'), dpi=150)
    plt.close(fig)
    # Box plot
    fig, ax = plt.subplots(figsize=(4, 6))
    ax.boxplot(loss, vert=True, showfliers=True)
    ax.set_ylabel('PPW % loss vs optimal')
    ax.set_title(f'PPW Loss Box Plot — {bench}')
    fig.tight_layout()
    fig.savefig(os.path.join(plot_dir, f'ppw_loss_box_{bench}.png'), dpi=150)
    plt.close(fig)
    out(f'  {bench}: saved plots -> {plot_dir}/ppw_loss_{{hist,cdf,box}}_{bench}.png')

# Comparison box plot across benchmarks -- generated ONCE, after the loop
# (moved out of the per-benchmark loop, which would otherwise regenerate
# and overwrite this same file on every iteration).
per_bench_losses = [subset(b)['pred_ppw_loss_pct'].dropna() for b in benchmarks[1:]]
non_empty = [(b, s) for b, s in zip(benchmarks[1:], per_bench_losses) if not s.empty]
if non_empty:
    labels, series_list = zip(*non_empty)
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.boxplot(series_list, tick_labels=list(labels))
    ax.set_ylabel('PPW % loss vs optimal')
    ax.set_title('PPW Loss by Benchmark')
    fig.tight_layout()
    fig.savefig(os.path.join(plot_dir, 'ppw_loss_box_comparison.png'), dpi=150)
    plt.close(fig)
    out(f'  Comparison plot saved -> {plot_dir}/ppw_loss_box_comparison.png')


section('ANALYSIS 2 — STATIC BASELINE COMPARISON')
out('  Metric: average PPW per period  (higher = better)')
out()
out(f'  {"Benchmark":<12} {"Optimal":>14} {"Best Static":>14} '
    f'{"Model Pred":>14} {"Worst Static":>14}')
out('  ' + '-' * 62)

for bench in sorted(static_configs.keys()):
    sc      = static_configs[bench]
    df_b    = subset(bench)
    vm      = df_b['pred_ppw_loss_pct'].notna() & df_b['best_ppw'].notna()
    model_avg = (df_b.loc[vm, 'best_ppw'] *
                 (1 - df_b.loc[vm, 'pred_ppw_loss_pct'] / 100)).mean()

    out(f'  {bench:<12} '
        f'{sc["optimal_avg_ppw"]:>14,.0f} '
        f'{sc["best_static_avg_ppw"]:>14,.0f} '
        f'{model_avg:>14,.0f} '
        f'{sc["worst_static_avg_ppw"]:>14,.0f}')

out()
out('  % gap vs optimal  (negative = worse than optimal):')
out(f'  {"Benchmark":<12} {"Best Static":>14} {"Model Pred":>14} {"Worst Static":>14}')
out('  ' + '-' * 48)

for bench in sorted(static_configs.keys()):
    sc   = static_configs[bench]
    df_b = subset(bench)
    opt  = sc['optimal_avg_ppw']
    if opt == 0 or np.isnan(opt): continue
    vm   = df_b['pred_ppw_loss_pct'].notna() & df_b['best_ppw'].notna()
    model_avg = (df_b.loc[vm, 'best_ppw'] *
                 (1 - df_b.loc[vm, 'pred_ppw_loss_pct'] / 100)).mean()

    out(f'  {bench:<12} '
        f'{(sc["best_static_avg_ppw"]  - opt)/opt*100:>+13.2f}% '
        f'{(model_avg                  - opt)/opt*100:>+13.2f}% '
        f'{(sc["worst_static_avg_ppw"] - opt)/opt*100:>+13.2f}%')

out()
out(f'  Static configs (order: {TARGET_KEYS}):')
for bench, sc in sorted(static_configs.items()):
    out(f'    {bench:<12}  best:  {sc["best_static"]}')
    out(f'    {"":<12}  worst: {sc["worst_static"]}')


section('ANALYSIS 3 — GAP BETWEEN BEST AND 2ND-BEST CONFIG')
out('  How much PPW do you lose by picking 2nd instead of 1st?')
out('  (Small gap -> 2nd is nearly as good; large gap -> 1st is critical)')

for bench in benchmarks:
    df_b = subset(bench)
    gap  = df_b['gap_best_2nd_pct'].dropna()
    subsection(bench.upper())
    if gap.empty:
        out('    No data.'); continue

    n_gap = len(gap)
    out(f'    Samples with gap data: {n_gap:,}')
    out(f'    Stats: {stats_str(gap)}')
    out()
    out(f'    Gap distribution (% of {n_gap:,} samples with PPW data):')

    for lo, hi, lbl in [
        (None, 0.5, '< 0.5%   (nearly identical)'),
        (0.5,  2,   '0.5-2%   (minor difference) '),
        (2,    5,   '2-5%     (moderate)          '),
        (5,    10,  '5-10%    (significant)        '),
        (10,   20,  '10-20%   (large)              '),
        (20,   None,'>20%     (critical choice)    '),
    ]:
        cnt = (gap <= hi).sum()           if lo is None  else \
              (gap >  lo).sum()           if hi is None  else \
              ((gap > lo) & (gap <= hi)).sum()
        out(f'      {lbl}  {cnt:>6,}  ({cnt/n_gap*100:5.1f}%)')

    df_b2 = df_b[df_b['gap_best_2nd_pct'].notna()]
    if len(df_b2) > 10:
        corr = df_b2['gap_best_2nd_pct'].corr(df_b2['exact_match'].astype(float))
        direction = '(larger gap -> easier to get right)' if corr >= 0 \
                    else '(larger gap -> harder to get right — CONCERNING)'
        out(f'    Corr(gap, exact_match): {corr:.3f}  {direction}')


section('ANALYSIS 4 — NO-CHANGE BASELINE  (Keep Previous Config)')
out("  If we always use the previous period's config instead of predicting,")
out('  how often is it still in the top 3, and how much PPW do we lose?')

if not prev_config_available:
    out('  [SKIP] Previous-config columns not found in data.')
else:
    for bench in benchmarks:
        df_b = subset(bench)
        n    = len(df_b)
        n_p  = int(df_b['prev_in_top3'].notna().sum())
        subsection(bench.upper())

        if n_p == 0:
            out('    No prev-config data.'); continue

        out(f'    Samples: {n:,}  (prev-config available: {n_p:,})')

        prev_best = df_b['prev_is_best'].sum()
        prev_top3 = df_b['prev_in_top3'].sum()

        out(f'    Prev config IS best:       {pct_str(prev_best, n_p)}')
        out(f'    Prev config in top-3:      {pct_str(prev_top3, n_p)}')
        out(f'    Prev config NOT in top-3:  {pct_str(n_p - prev_top3, n_p)}')

        loss = df_b['prev_ppw_loss_pct'].dropna()
        out(f'    PPW % loss stats: {stats_str(loss)}')
        loss_buckets(df_b['prev_ppw_loss_pct'], n_p, label='No-change baseline ')

        out()
        out('    Model vs No-Change comparison:')
        m_loss  = df_b['pred_ppw_loss_pct'].dropna().mean()
        nc_loss = loss.mean() if len(loss) > 0 else float('nan')

        out(f'      {"":32} {"Model":>10}   {"No-Change":>10}')
        out(f'      {"Exact / Is-Best match":32} '
            f'{pct_str(df_b["exact_match"].sum(), n)}   '
            f'{pct_str(prev_best, n_p)}')
        out(f'      {"Top-3 match":32} '
            f'{pct_str(df_b["top3_match"].sum(), n)}   '
            f'{pct_str(prev_top3, n_p)}')
        out(f'      {"Avg PPW % loss":32} {m_loss:>9.2f}%   {nc_loss:>9.2f}%')
        winner = 'MODEL' if m_loss < nc_loss else 'NO-CHANGE'

        out(f'      -> {winner} has lower average PPW loss '
            f'(delta = {abs(m_loss - nc_loss):.2f}%)')


section('ANALYSIS 5 - INFERENCE & RECONFIGURATION OVERHEAD')

TECH_PARAMS = {
    'tech_node_nm': 45,
    'clock_rate_mhz': 2660,
    'vdd': 1.2,
    'device_type': 'HP',
    'btb_entries_default': 18944,
    'l2_capacity_kb': 256,
    'l3_capacity_kb': 8192,
    'E_gate_per_btb_entry_pJ': 0.05,
    'E_gate_per_l2_kb_pJ': 2.5,
    'E_gate_per_l3_kb_pJ': 1.8,
    'E_gate_per_prefetcher_pJ': 15.0,
    'E_rf_inst_pJ': 0.5,
    'E_rf_cmp_pJ': 0.1,
    'E_rf_mem_pJ': 1.0,
}

out('  McPAT/GAINESTOWN PARAMETERS USED:')
out('  ' + '-' * 50)
out(f"  Technology Node:      {TECH_PARAMS['tech_node_nm']} nm")
out(f"  Core Clock:           {TECH_PARAMS['clock_rate_mhz']} MHz")
out(f"  Supply Voltage (Vdd): {TECH_PARAMS['vdd']} V")
out(f"  Device Type:          {TECH_PARAMS['device_type']} (High Performance)")
out()
out('  Component Parameters:')
out(f"    BTB entries (default):  {TECH_PARAMS['btb_entries_default']}")
out(f"    L2 capacity:            {TECH_PARAMS['l2_capacity_kb']} KB")
out(f"    L3 capacity:            {TECH_PARAMS['l3_capacity_kb']} KB")
out()
out('  Energy Parameters (45nm HP, 1.2V):')
out(f"    E_gate_per_btb_entry:   {TECH_PARAMS['E_gate_per_btb_entry_pJ']:.3f} pJ")
out(f"    E_gate_per_l2_kb:       {TECH_PARAMS['E_gate_per_l2_kb_pJ']:.3f} pJ")
out(f"    E_gate_per_l3_kb:       {TECH_PARAMS['E_gate_per_l3_kb_pJ']:.3f} pJ")
out(f"    E_gate_per_prefetcher:  {TECH_PARAMS['E_gate_per_prefetcher_pJ']:.3f} pJ")

if args.cost_csv and os.path.exists(args.cost_csv):
    out()
    out(f"  Cost analysis loaded from: {args.cost_csv}")
    cost_df = pd.read_csv(args.cost_csv)

    if 'inference_energy_pJ' in cost_df.columns:
        inf_e = cost_df['inference_energy_pJ'].iloc[0]
        out()
        out('  INFERENCE COST (per 500K inst interval):')
        out('  ' + '-' * 50)
        out(f"    Total inference:  {inf_e:.2f} pJ ({inf_e/1e6:.4f} uJ)")

    if 'reconfig_energy_pJ' in cost_df.columns:
        n_changes = (cost_df['config_changed'] == True).sum() if 'config_changed' in cost_df.columns else 0
        total_reconfig = cost_df['reconfig_energy_pJ'].sum()
        avg_reconfig = cost_df[cost_df['reconfig_energy_pJ'] > 0]['reconfig_energy_pJ'].mean() if n_changes > 0 else 0

        out()
        out('  RECONFIGURATION COST (only on config change):')
        out('  ' + '-' * 50)

        out('  Component     | Energy/change | % intervals changed')
        out('  ' + '-' * 55)

        if 'l2_changed' in cost_df.columns:
            l2_changes = cost_df['l2_changed'].sum()
            l2_pct = l2_changes / (len(cost_df) - 1) * 100 if len(cost_df) > 1 else 0
            out(f"    L2 cache      | {TECH_PARAMS['E_gate_per_l2_kb_pJ']:.1f} pJ/KB  | {l2_pct:.1f}%")

        if 'l3_changed' in cost_df.columns:
            l3_changes = cost_df['l3_changed'].sum()
            l3_pct = l3_changes / (len(cost_df) - 1) * 100 if len(cost_df) > 1 else 0
            out(f"    L3 cache      | {TECH_PARAMS['E_gate_per_l3_kb_pJ']:.1f} pJ/KB  | {l3_pct:.1f}%")

        if 'btb_changed' in cost_df.columns:
            btb_changes = cost_df['btb_changed'].sum()
            btb_pct = btb_changes / (len(cost_df) - 1) * 100 if len(cost_df) > 1 else 0
            out(f"    BTB (c0+c1)   | N/A           | {btb_pct:.1f}%")

        if 'prefetcher_changed' in cost_df.columns:
            pf_changes = cost_df['prefetcher_changed'].sum()
            pf_pct = pf_changes / (len(cost_df) - 1) * 100 if len(cost_df) > 1 else 0
            out(f"    Prefetcher    | {TECH_PARAMS['E_gate_per_prefetcher_pJ']:.1f} pJ      | {pf_pct:.1f}%")

        out()
        out(f"    Total reconfig:      {total_reconfig:.2f} pJ")
        out(f"    Avg per change:      {avg_reconfig:.2f} pJ" if n_changes > 0 else "    Avg per change:      N/A (no changes)")
        out(f"    Avg per interval:    {total_reconfig/(len(cost_df)-1):.2f} pJ" if len(cost_df) > 1 else "    N/A")

    if 'net_ppw' in cost_df.columns and 'PPW_best' in cost_df.columns:
        raw_ppw = cost_df['PPW_best'].dropna().mean()
        net_ppw = cost_df['net_ppw'].dropna().mean()

        out()
        out('  NET PPW IMPACT:')
        out('  ' + '-' * 50)
        out(f"    Raw PPW (best config):     {raw_ppw:.4e}")
        out(f"    Net PPW (with overhead):   {net_ppw:.4e}")
        if raw_ppw > 0:
            overhead_pct = (raw_ppw - net_ppw) / raw_ppw * 100
            out(f"    PPW overhead:              {overhead_pct:.2f}%")
else:
    out()
    out('  [SKIP] No cost analysis CSV provided.')
    out('  Run costAnalysis.py first: python costAnalysis.py --benchmark <name> --model-dir saved_models/')


report_ts   = datetime.now().strftime('%Y%m%d_%H%M%S')
report_path = os.path.join(args.output_dir, f'analysis_report_{report_ts}.txt')
with open(report_path, 'w') as f:
    f.write('\n'.join(report_lines))

out()
out(f'Report saved -> {report_path}')
